var last = function (arr) { return arr[arr.length - 1]; };
var l1 = last(['p', 'z']);
var lasta = function (arr) { return arr[arr.length - 1]; };
var l4 = lasta([5, 'p', 'z']);
var lastT = function (arr) { return arr[arr.length - 1]; };
var l3 = lastT([1, 2, 3]);
var l5 = lastT(['z', 'z', 'z']);
var l6 = lastT([1, 2, 3]);
var concatAB = function (a, b) { return "".concat(a, " && ").concat(b); };
concatAB(5, 7);
var concatABT = function (a, b) { return "".concat(a, " && ").concat(b); };
concatABT('z', 'x');
